## 0x3C 异常

### 自定义运行时异常

- 定义一个异常类继承 $RuntimeException$
- 重写构造器
- 通过 `throw new 异常类(xxx)` 来创建异常对象并抛出。
- 编译阶段不报错，提醒不强烈，运行时才可能出现

#### 用例

```java
// Main.java
public class Main {
    public static void main(String[] args){
        try {
            saveAge(223);
            System.out.println("底层执行成功");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("底层出现了bug");
        }
    }

    public static void saveAge(int age) {
        if (age > 0 && age < 150) {
            System.out.println("年龄保存成功" + age);
        } else {
            // throw 抛出去这个异常对象
            throw new AgeIllegalRuntimeException("/age is illegal, your age is " + age);
        }
    }
}

// AgeIllegalRuntimeException.java
public class AgeIllegalRuntimeException extends RuntimeException {
    public AgeIllegalRuntimeException() {
    }

    public AgeIllegalRuntimeException(String message) {
        super(message);
    }
}
```

### 自定义编译时异常

- 定义一个异常类继承 $Exception$
- 重写构造器
- 通过 `throw new 异常类(xxx)` 来创建异常对象并抛出
- 编译阶段就报错，提醒更加强烈

```java
// Main.java
public class Main {
    public static void main(String[] args){
        try {
            saveAge(223);
            System.out.println("底层执行成功");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("底层出现了bug");
        }
    }

    public static void saveAge(int age) throws AgeIllegalException {
        if (age > 0 && age < 150) {
            System.out.println("年龄保存成功" + age);
        } else {
            // throw 抛出去这个异常对象
            // throws 用在方法上，抛出方法内部的异常
            throw new AgeIllegalException("/age is illegal, your age is " + age);
        }
    }
}

// AgeIllegalException.java
public class AgeIllegalException extends Exception {
    public AgeIllegalException() {
    }

    public AgeIllegalException(String message) {
        super(message);
    }
}
```

### 异常的两种处理方式

1. 捕获异常，记录异常并响应合适的信息给用户

   ```java
   public class Main {
       public static void main(String[] args){
           try {
               test1();
           } catch (Exception e) {
               System.out.println("您当前操作有问题！！");
               e.printStackTrace();    // 打印异常信息
           }
       }

       public static void test1() throws Exception {
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
           Date d = sdf.parse("2028-11-11 10:24"); // 错误
           System.out.println(d);
           test2();
       }

       public static void test2() throws Exception {
           InputStream is = new FileInputStream("D:/movie.png");   // 错误
       }
   }
   ```

2. 捕获异常，尝试重新修复
   
    ```java
    public class Main {
        public static void main(String[] args){
            while (true) {
                try {
                    System.out.println(getMoney());
                    break;
                } catch (Exception e) {
                    System.out.println("请输入合法数字！！！");
                }
            }
        }

        public static double getMoney() {
            Scanner sc = new Scanner(System.in);
            System.out.println("请您输入合适的价格：");
            while (true) {
                double money = sc.nextDouble();
                if (money >= 0) {
                    return money;
                } else {
                    System.out.println("您输入的价格是不合适的！");
                }
            }
        }
    }
    ```